### ISSUE TITLE
Request adding Y: -9999 to importer

### ISSUE THREAD

**Issue by ghost** [advancedfx/afx-blender-scripts#1]
Mostly _if not even all_ users of the script use this to export as FBX afterwards to a software or similar like:
„Cinema 4D“/„3ds Max“,
„Unreal Engine“,
...

The workflow of removing temporary unwanted meshes _(for example meshes which are not being used yet or are done being used and float around the scene)_ from the scene is to add keyframes (1 before and 1 after the animation(s)) and set the Y attribute to -9999.

The only common denominator between all software is the Y attribute.
So maybe add an checkbox which adds, while/after importing, keyframes (-1 +1) to the animations (even if it has multiple ones) and set the Y to -9999 to these keyframes.

Determinator is already existent afaik and is called hide_render.

Would save _us all_ lots of hours.

Sincerly,
the editing community

**Comment by dtugend** [comment]
@can92 Can you please test if the [latest release](https://github.com/ripieces/afx-blender-scripts/releases/latest) (currenlty v1.4.2 (2017-11-18T20:00Z)) added the enchancement in a suitable way? I can also add moving it away on Y axis if required, but if scaling to 0 solves it for now, I'd like to leave it taht way.
