### ISSUE TITLE
errors when installing addon in blender

### ISSUE THREAD

**Issue by Rainerr123** [advancedfx/afx-blender-scripts#12]
i select install in blender 2.18a and it comes up with the error pinned

![image](https://user-images.githubusercontent.com/57333628/73598227-85b35e80-4570-11ea-8a9a-bf70d38ad8b0.png)

**Comment by dtugend** [comment]
Please read the https://github.com/advancedfx/afx-blender-scripts/blob/master/advancedfx/readme.txt

You probably forgot to install Blender Source Tools 3.0.1 first.

**Comment by dtugend** [comment]
Closing due to lacking feedback.
