### ISSUE TITLE
Gloves distortion

### ISSUE THREAD

**Issue by Gendos100500** [advancedfx/afx-blender-scripts#25]
Sup, gloves after agr importing so glitching 
![unknown (1)](https://user-images.githubusercontent.com/47818872/97770800-56269680-1b82-11eb-878d-8a1db5ca0a47.png)

**Comment by dtugend** [comment]
Please provide more information:

1. Is the glove actually used by any player in the AGR?
1. Which version of HLAE are you using?
2. Which version of Blender Source Tools are you using?
3. Which version of afx-blender-scripts are you using?
4. Which version of Crowbar are you using?
5. When did you last update the models from Crowbar?
6. What are you AGR / other recording settings (e.g. mirv_agr recordInvisible? cl_custom_material_override etc)?
7. Consider providing a demo / the AGR file.

**Comment by dtugend** [comment]
We can not solve this issue without further information requested above.
