### ISSUE TITLE
Wrong rotation on viewmodel when importing

### ISSUE THREAD

**Issue by exellian** [advancedfx/afx-blender-scripts#27]
![alt text](https://i.imgur.com/fuULldS.png)

I have recorded the agr with:

host_timescale 0; 
host_framerate 60; 
mirv_streams record agr enabled 1; 
mirv_streams record agr recordPlayers 1;  
mirv_streams record agr recordCamera 1; 
mirv_streams record agr recordViewmodel 1;
mirv_streams record agr recordWeapons 1;
mirv_streams record agr recordInvisible 0; 
mirv_streams record agr recordProjectiles 0;

And imported it with the 1.12 version of afx-blender-scripts with blender-source-tools 3.1.1 and 3.1.0 both didn't work

**Comment by dtugend** [comment]
```
cl_righthand 1
```
in console should fix it

**Comment by exellian** [comment]
It fixed it
