### ISSUE TITLE
.agr import problem: "ERROR: Version 4 is not supported" 

### ISSUE THREAD

**Issue by AnLy123** [advancedfx/afx-blender-scripts#36]
When I try to import .agr I get the error "ERROR: Version 4 is not supported"

**Comment by dtugend** [comment]
Your AGR has been recorded with an outdated HLAE version, please make sure to use the [latest HLAE version](https://github.com/advancedfx/advancedfx/releases/latest) next time.

You would have to use an older plugin to import the old / outdated version 4:
https://github.com/advancedfx/afx-blender-scripts/releases/tag/v1.10.4

**Comment by AnLy123** [comment]
Thanks!
