### ISSUE TITLE
No movement after importing AGR from CSGO

### ISSUE THREAD

**Issue by ghost** [advancedfx/afx-blender-scripts#37]
As the title suggests, I am unable to get any movement out of the cameras, player, gun models, ext after importing them into my blender scene.  I initially tried to demo record a old 2016 demo and have tried a recent game of mine played yesterday.  

HLAE Settings:
host_timescale 0;
host_framerate 30;
mirv_streams record agr enabled 1;
mirv_streams record agr recordPlayers 1;
mirv_streams record agr recordCamera 1;
mirv_streams record agr recordInvisible 0;
mirv_streams record agr recordWeapons 1;
mirv_streams record agr recordProjectiles 0;
mirv_streams record agr recordViewmodel 1;

Blender FPS: 30
SPECS: CPU- Ryzen 7 3800x 8core, 32GB Ram, RTX 3060 12GB VRam

https://user-images.githubusercontent.com/44033370/171072266-04545e5f-ab6b-4528-bdfd-2c3b37a8fc00.mp4

**Comment by dtugend** [comment]
1. Was the demo playing while you recorded the AGR or paused?
2. Which Blender Source Tools and AGR Plugin(s) and which exact versions you used?
3. What is that NULL object you are parenting too? Where does it come from, the original importer doesn't create it? Does it work before moving them into that?
4. Which game and version of the game is this? Official Steam CSS? CSSV34?

You might get a faster response in the HLAE AGR Discord of @Devostated : https://discord.gg/wd8Rcdj

**Comment by ghost** [comment]
> 1. Was the demo playing while you recorded the AGR or paused?
> 2. Which Blender Source Tools and AGR Plugin(s) and which exact versions you used?
> 3. What is that NULL object you are parenting too? Where does it come from, the original importer doesn't create it? Does it work before moving them into that?
> 4. Which game and version of the game is this? Official Steam CSS? CSSV34?
> 
> You might get a faster response in the HLAE AGR Discord of @Devostated : https://discord.gg/wd8Rcdj



1A.) Yep, I made sure to press play and record all the way through and then I paused the video and executed the "mirv_streams record stop" command at my desired endpoint. 

2A.) Blender Source Tools 3.2.2 and afx-blender-scripts_1_14_1 (my addons folder and HLAE screenshot below)

3A.) Currently I am following a tutorial on YT, the creator adds an "empty > plain axis" and parents the camera and characters to it by dragging all the cams and characters and dropping them on the empty while holding shift. Even when I skipped this step and tried to play the animation the same error persisted no movement.   

4A.) This game is CounterStrike-Global Offensive Official Steam. (I don't know how to check the game version but I haven't done anything different to it.


![Untitled](https://user-images.githubusercontent.com/44033370/171182014-07351a9d-cf2f-4353-b2a8-df843816d4cb.jpg)
)

**Comment by Devostated** [comment]
Hey, it seems like you used the "enhanced" importer, which is a third party tool. Could you try to just use the official importer? And feel free to send me the AGR, so I can take a look at it.

**Comment by dtugend** [comment]
> (I don't know how to check the game version

Enter `version` into console:
```
] version
Protocol version 13832 [1463/1463]
Exe version 1.38.3.2 (csgo)
Exe build: 15:25:34 May 23 2022 (8598) (730)
Windows version 6.2
Steam beta name: 
```

As devostated said, if you are using `File -> Import -> HLAE afxGameRecord (enhanced) (.agr)`, that "enhanced" version is provided by https://github.com/lasa01/io_import_vmf, not us.  
In that case you might want to try the latest version by lasa first, there has been an update meanwhile.  
We can only try to help if it happens with the original importer, if the enhanced one is bugged, you'd have to kindly ask lasa01 instead please.

**Comment by ghost** [comment]
> > (I don't know how to check the game version
> 
> Enter `version` into console:
> 
> ```
> ] version
> Protocol version 13832 [1463/1463]
> Exe version 1.38.3.2 (csgo)
> Exe build: 15:25:34 May 23 2022 (8598) (730)
> Windows version 6.2
> Steam beta name: 
> ```
> 
> As devostated said, if you are using `File -> Import -> HLAE afxGameRecord (enhanced) (.agr)`, that "enhanced" version is provided by https://github.com/lasa01/io_import_vmf, not us. In that case you might want to try the latest version by lasa first, there has been an update meanwhile. We can only try to help if it happens with the original importer, if the enhanced one is bugged, you'd have to kindly ask lasa01 instead please.

Thank you for that piece of information! Here is my console output:

Protocol version 13832 [1463/1463]
Exe version 1.38.3.2 (csgo)
Exe build: 15:25:34 May 23 2022 (8598) (730)
Windows version 6.2
Steam beta name:

**Comment by ghost** [comment]
> Hey, it seems like you used the "enhanced" importer, which is a third party tool. Could you try to just use the official importer? And feel free to send me the AGR, so I can take a look at it.

You are correct I am using the enhanced importer I can give the official importer a try now. Here is the AGR as well. The file was too large to upload while only being 250MBs so here a mega.nz link.

https://mega.nz/file/cFA2XJLI#BL-l_TqQXf_a0aAOqFIiH0WLrgB014bYHZuF9Uqubuc

**Comment by Devostated** [comment]
> 

The AGR you sent works. It's just not doing anything the first ~1400 frames and last ~400. I assume it's cause you started recording before playing/resuming the demo and pausing the demo before ending the recording.

**Comment by ghost** [comment]
> > 
> 
> The AGR you sent works. It's just not doing anything the first ~1400 frames and last ~400. I assume it's cause you started recording before playing/resuming the demo and pausing the demo before ending the recording.

Holy Smokes you're right!! I can see the movement now perhaps this has been the problem all along. I imported the same AGR with the Official importer and I got these errors for importing (below) but the animation still played through. I will try again with the enhanced since there was no importing errors THANK YOU A TON!


![Untitled](https://user-images.githubusercontent.com/44033370/171219160-1e847c00-20a5-4250-a2b6-efd2be93b2f5.jpg)

**Comment by Devostated** [comment]
Enhanced importer takes all needed files from the game, the official one uses your decompiled models folder. I assume something went wrong during your decompiling.  Those are my decompiled models, which don't give the error: http://bit.ly/CSGO_Models

**Comment by dtugend** [comment]
I'd recommend Lasa01's enhanced importer if it works for you, it's just we can not help much in case it bugs out while the official one doesn't.

**Comment by ghost** [comment]
> Enhanced importer takes all needed files from the game, the official one uses your decompiled models folder. I assume something went wrong during your decompiling. Those are my decompiled models, which don't give the error: http://bit.ly/CSGO_Models

Sweet thank you so much for the resources everything works fine with both importers just a few bugged models. Assuming everything will go well with the linked models, all is solved.
