### ISSUE TITLE
Can not install plugin to blender

### ISSUE THREAD

**Issue by viasux** [advancedfx/afx-blender-scripts#4]
![wtf](https://user-images.githubusercontent.com/47131867/59163495-cc6eb880-8ab6-11e9-85d9-ff10a293fbf4.PNG)
This happened when I tried to install

**Comment by dtugend** [comment]
You are using Blender 2.79b, you need to use the older v1.6.0 for that, v1.7.0 is for newer Blender 2.8.

**Comment by dtugend** [comment]
Closing due to no feedback.
