### ISSUE TITLE
How do I specify the asset path for importing .agr files?

### ISSUE THREAD

**Issue by TheLazySquid** [advancedfx/afx-blender-scripts#41]
I've been trying to get .agr files working in blender for a while now. After reading the readme for this, it looks like I need to specify the "asset path" for where decompiled assets should be stored. I've already managed to decompile the assets with Crowbar, and now have them sitting in a folder. How can I specify where the program should look for them?
Thanks!

**Comment by dtugend** [comment]
The asset path is set in the import dialogue for the HLAE afxGameRecord (.agr) import Dialogue:
![image](https://user-images.githubusercontent.com/3610128/210149596-f0c84963-51b7-4de0-878e-3da7c8151322.png)

If you have further questions and happen to be able to use Discord I can recommend the Discord server run by Devo:
AGR TechSupport
https://discord.gg/wd8Rcdj

**Comment by TheLazySquid** [comment]
Thanks! I had managed to completely miss that.
