### ISSUE TITLE
Source tools Error Report

### ISSUE THREAD

**Issue by DarkSamurai096** [advancedfx/afx-blender-scripts#42]
Hello, I ran into a problem when importing a demo from cs:go using afx blender scripts. Source tools Error Report. Pls help
![Снимок экрана (6)](https://github.com/advancedfx/afx-blender-scripts/assets/141944237/5774d47e-58c1-4cd0-9c02-d9be606b2067)
![Снимок экрана (7)](https://github.com/advancedfx/afx-blender-scripts/assets/141944237/e296a191-f590-4da6-9e13-3f8937fd3282)

**Comment by Devostated** [comment]
remove models from the path

**Comment by DarkSamurai096** [comment]
OH MY GOD THANK YOU!
