### ISSUE TITLE
Can't import AGR (afx-blender-scripts 1.14.2) 

### ISSUE THREAD

**Issue by Slopz** [advancedfx/afx-blender-scripts#43]
Keeps happening randomly, sometimes restarting Blender fixes it. 

Python: Traceback (most recent call last):
  File "C:\Users\N\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\advancedfx\import_agr.py", line 559, in execute
    bpy.utils.unregister_class(vs_import_smd.SmdImporter)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\N\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\advancedfx\import_agr.py", line 563, in execute
    bpy.utils.unregister_class(SmdImporterEx)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

**Comment by dtugend** [comment]
Hi.

Probably you are missing dependencies of the script that need to be installed first (e.g. Blender Source Tools).
See https://github.com/advancedfx/afx-blender-scripts/blob/main/advancedfx/readme.txt for more details.
