### ISSUE TITLE
No clear or side menu option

### ISSUE THREAD

**Issue by AdyStudios** [advancedfx/afx-blender-scripts#45]
Hi! I might just be missing something, but there is no side menu for AGR. This one: 
![image](https://github.com/advancedfx/afx-blender-scripts/assets/74962285/b8116bf7-154e-471b-b7ec-e54d535a84f1)

How/where can I find this?

**Comment by Devostated** [comment]
The provided screenshot is not from our addon.

**Comment by AdyStudios** [comment]
> The provided screenshot is not from our addon.

Wait sorry, which addon is that?

**Comment by AdyStudios** [comment]
Found it, sorry: [io_scene_CSGO](https://github.com/adenexvfx/io_scene_CSGO)
